# Generated by Django 5.2.6 on 2025-09-25 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_category_name_alter_post_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="statut",
            new_name="status",
        ),
    ]
